# =============================
# Server Configuration
# =============================
server:
  port: 8080
  servlet:
    context-path: /

# =============================
# Spring Datasource (Database)
# =============================
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/zuzu
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

# =============================
# Logging
# =============================
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.zuzureviewsystem: DEBUG
  file:
    name: logs/application.log

# =============================
# Application-specific Settings
# =============================
app:
  name: ZuzuReviewSystem
  version: 1.0.0
